# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0002_auto_20160610_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='keyword',
        ),
        migrations.AddField(
            model_name='keyword',
            name='urls',
            field=models.ManyToManyField(to='google.URL'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
